### ISSUE TITLE
verification_data/1.1-image 

### ISSUE THREAD

**Issue by Mahmoud-Elbarrawy** [OBPMark/OBPMark#21]
Verification data for image processing in case of 2048, and 4096 folders is not correct the output.bin is not the same as 1.1-image-output_02.bin and 1.1-image-output_03.bin.
I used Linux utils to compare the binary fills,`cmp` and `diff`.

**Comment by jaquerinte** [comment]
Fix in commit e1840b188a315c26cb1e83cc392fe846d83b4d65 on master
