### ISSUE TITLE
Missing input_data

### ISSUE THREAD

**Issue by zhenyu818** [OBPMark/OBPMark#26]
Hello, thank you for your contribution. I tried compiling each benchmark in the CUDA version using `./compile_all.sh cuda`, then ran 3.1-aes_encryption with the command `./obpmark-3.1-aes_encryption_cuda -k 128 -l 128`. However, I encountered an error: `error: failed to open file: ../../data/input_data/3.1-aes_encryption/128/3.1-aes_encryption-data_128.bin`. I noticed that there is no `3.1-aes_encryption-data_128.bin` file in the `./../data/input_data/3.1-aes_encryption/128/` directory. Could it be that some input data is missing? Additionally, the README files for each benchmark are also empty.

**Comment by jaquerinte** [comment]
Hi @zhenyu818, yes the individual README is something that requiereds some work to be polish. I think for the status of the issue that you found out that the data is in the GIT LFS. We will try to make it more clear on the documentation. Sorry for the issues.
